language: python
python:
  - 2.7
  - 3.4
  - 3.5

env:
  - python: 2.7
    TOX_ENV=py27-twlatest
  - python: 2.7
    TOX_ENV=py27-twtrunk
  - python: 2.7
    TOX_ENV=py27-tw162
  - python: 2.7
    TOX_ENV=py27-tw160
  - python: 2.7
    TOX_ENV=py27-tw150
  - python: 2.7
    TOX_ENV=py27-tw140
  - python: 3.4
    TOX_ENV=py34-twtrunk
  - python: 3.5
    TOX_ENV=py35-twtrunk
  - python: 2.7
    TOX_ENV=linters

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py34-twtrunk
    - env: TOX_ENV=py35-twtrunk

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls

notifications:
    email: false
